openapi: 3.0.3
info:
  title: CO Cupon API
  description: |-
    CO Cupon es una API responsable por entregar la lista de items favoritos mas costosa que puede ser comprada 
    
    Algunos links de utilidad:
    - [CO Cupon repositorio](https://github.com/antoniodi/COCupon.git)
    - [La definicion del API para Cupon](https://github.com/antoniodi/COCupon/blob/master/docs/COCuponAPI.yaml)
  contact:
    email: anthonydicortes@gmail.com
  version: 1.0.0
servers:
  - url: TBD
tags:
  - name: Cupon
    description: Permite encontrar la lista de items favoritos mas costosa que se puede comprar con un cupón sin superar su valor
paths:
  /coupon:
    post:
      tags:
        - pet
      summary: Encuentra la lista de compra sugerida de mayor valor que se puede comprar con un cupon sin superar su valor
      description: Encuentra la lista de compra sugerida de mayor valor que se puede comprar con un cupon sin superar su valor
      operationId: obtenerListaDeCompraSugerida
      requestBody:
        description: Encuentra la lista de compra sugerida de mayor valor que se puede comprar
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemsFavoritosYCuponRequestDto'
        required: true
      responses:
        '200':
          description: Existe una lista de compra sugerida con al menos un producto que se puede comprar con el valor del cupon
          content:
            application/json:
              schema:
                $ref: '#/components/requestBodies/ListaDeCompraSugeridaResponseDto'
        '404':
          description: El valor del cupon no es suficiente como para comprar al menos un item

components:
  schemas:
    ItemsFavoritosYCuponRequestDto:
      required:
        - item_ids
        - amount
      type: object
      properties:
        item_ids:
          type: array
          items:
            type: string
          example: ["MLA1", "MLA2", "MLA3", "MLA4", "MLA5"]
        amount:
          type: integer
          format: int
          example: 500
  requestBodies:
    ListaDeCompraSugeridaResponseDto:
      content:
      type: object
      properties:
        item_ids:
          type: array
          items:
            type: string
          example: ["MLA1", "MLA2", "MLA3", "MLA4", "MLA5"]
        total:
          type: integer
          format: int
          example: 500